export const SESSION_EXPIRED = "SESSION_EXPIRED";
export const SESSION_TO_INIT = "SESSION_TO_INIT";
export const SESSION_OK = "SESSION_OK";

export const AUTH_LEVEL_ADMIN = "ADMIN";
export const AUTH_LEVEL_ANIMATORE = "ANIMATORE";
export const AUTH_LEVEL_ISCRITTORE = "ISCRITTORE";

export const PLAYER_PAGE_CREATE_MODE = "CREATE";
export const PLAYER_PAGE_UPDATE_MODE = "UPDATE";
export const PLAYER_PAGE_VIEW_MODE = "VIEW";

export const DEFAULT_2W_STANDARD = 50;
export const DEFAULT_1W_STANDARD = 30;
export const DEFAULT_2W_BROTHER = 40;
export const DEFAULT_1W_BROTHER = 30;